### ISSUE TITLE
errors during `git commit`

### ISSUE THREAD

**Issue by pratik705** [fisadev/fisa-vim-config#103]
Getting below error during `git commit`:
<snip>
# git commit
Error detected while processing /root/.vimrc:
[...]
line   37:
E492: Not an editor command: Plug 'arielrossanigo/dir-configs-override.vim'
line   39:
E492: Not an editor command: Plug 'scrooloose/nerdtree'
line   41:
E492: Not an editor command: Plug 'scrooloose/nerdcommenter'
line   43:
E492: Not an editor command: Plug 'majutsushi/tagbar'
line   45:
E492: Not an editor command: Plug 'ctrlpvim/ctrlp.vim'
line   47:
E492: Not an editor command: Plug 'fisadev/vim-ctrlp-cmdpalette'
line   49:
E492: Not an editor command: Plug 'mattn/emmet-vim'
line   51:
[...]
</snip>

**Comment by fisadev** [comment]
Hi!

This is probably because you don't have the plugin manager installed. Its installation may have failed during the first boot after you downloaded the plugin. Did you have git installed? Did it raise any errors?

The easiest way would be to delete your .vim folder, and run vim again, making sure the installation runs smoothly.
