### ISSUE TITLE
.vimrc not working in termux.

### ISSUE THREAD

**Issue by darkwarrior3** [fisadev/fisa-vim-config#117]
I I've followed everything written on website and I got these two errors.
![IMG_20191214_162750](https://user-images.githubusercontent.com/35144881/70847814-d35cf600-1e60-11ea-8ec7-e818bdb8ea9d.jpg)
![Screenshot_2019-12-14-16-19-50-693_com termux](https://user-images.githubusercontent.com/35144881/70847817-d7891380-1e60-11ea-9cd3-7203365e9a5e.jpg)
Please help

**Comment by xeffyr** [comment]
In Termux you need `vim-python` to be installed to have support for Python.

**Comment by darkwarrior3** [comment]
> In Termux you need `vim-python` to be installed to have support for Python.

After pkg install vim-python, I got this error

**Comment by darkwarrior3** [comment]
> In Termux you need `vim-python` to be installed to have support for Python.

**Comment by darkwarrior3** [comment]
> In Termux you need `vim-python` to be installed to have support for Python.

After pkg install vim-python, I got some error while launching vim
![IMG_20191226_215651](https://user-images.githubusercontent.com/35144881/71483463-ee9b0e80-282d-11ea-88d5-95e562dca537.jpg)

So I typed ```pip install neovim``` as it said requires one of neovim or pynvim.
From this it started to install both pynvim and neovim.
Then during these process I encountered these errors:-
![IMG_20191226_215603_593](https://user-images.githubusercontent.com/35144881/71483483-0a9eb000-282e-11ea-96b3-7be45d1ec03a.jpg)
![IMG_20191226_215605_124](https://user-images.githubusercontent.com/35144881/71483484-0b374680-282e-11ea-8cf0-ba72ad917db9.jpg)


Also on reddit:- https://reddit.com/r/termux/comments/efiak7/need_vimrc_for_python_ide_for_termux_fisa_is/fc2zi53?context=3

**Comment by fisadev** [comment]
Hi!

I can't help you on how to install packages on that environment, because I'm not familiar with termux and the hacks it might need to be able to run. But some usefull tips that come to my mind are:

- Be sure to install and match the dependencies required by the config, as stated in the install instructions at vim.fisadev.com. Specifically: have a vim with python support, install git, curl, python3-pip, exuberant-ctags and ack-grep as system packages, and install pynvim, flake8, pylint and isort using pip**3** (not just pip, but pip3, for python3)

- Make sure the "auto" installation runs on an environment that has all these dependencies installed. If you copied the config and ran vim with it but not having all the dependencies, you might have ended up with a broken installation (maybe some plugins didn't install correctly). I would suggest removing the `.vim` folder and letting the automatic installation run again.
