### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by cws999** [fisadev/fisa-vim-config#119]
I installed it according to [it](https://vim.fisadev.com/), step by step
The message is this

E484: Cannot open file /home/****/.vim/autoload/plug.vim
E117: Unknown function: plug#begin
E492: Not an vim command: Plug 'arielrossanigo/dir-configs-override.vim'
............
Have you tested it?
Have you tested it?
Have you tested it?

**Comment by fisadev** [comment]
This probably means that you lost internet connection or had some download error during the installation of vim-plug, otherwise it should be there because of the curl command that is executed on first time. So vim-plug wasn't able to be installed, and you ended up with a broken config. You can just delete the `.vim` folder and try again.

And yes, I did test it, plus it works correctly for hundreds of people. Try not to be rude like that, specially when using something other people gave you for free :)
